#!/usr/bin/env python3
"""
db_export.py – version-agnostic Supabase/PostgreSQL backup exporter.

pg_dump refuses to run against a server whose major version is NEWER than the
local client (e.g. pg_dump 16 vs PostgreSQL 17). This exporter uses psycopg2
directly, so it works regardless of the server version.

Output: backups/full_<timestamp>.tar.gz containing:
  - database.sql      DDL (tables, columns, defaults, PKs, uniques, FKs, indexes, sequences)
  - data/<table>.csv  all rows of every table in the public schema (and storage tables)
  - manifest.json     run metadata + per-table row counts

Usage: python3 db_export.py [--out-dir backups]
Restore: most tables are plain data + DDL from database.sql; see backup_db.sh.
"""

import argparse
import csv
import gzip
import io
import json
import os
import sys
import tarfile
from datetime import datetime, timezone

import psycopg2
from psycopg2 import sql

SCHEMAS = ("public", "storage")


def connect():
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from dotenv import load_dotenv

    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"), override=True)
    url = os.getenv("DATABASE_URL", "")
    if not url:
        raise SystemExit("DATABASE_URL missing from .env")
    url = url.replace("postgresql+asyncpg://", "postgresql://")
    url = url.replace("?ssl=require", "?sslmode=require")
    return psycopg2.connect(url)


def _quote_ident(cur, name, schema="public"):
    return cur.execute("SELECT quote_ident(%s), quote_ident(%s)", (schema, name)) or None


def get_server_info(cur):
    cur.execute("SELECT version(), current_database()")
    row = cur.fetchone()
    return {"server_version": row[0] if row else "unknown"}


def list_tables(cur):
    cur.execute(
        """
        SELECT table_schema, table_name
          FROM information_schema.tables
         WHERE table_schema IN %s
           AND table_type = 'BASE TABLE'
         ORDER BY table_schema, table_name
        """,
        (SCHEMAS,),
    )
    return cur.fetchall()


def dump_ddl(cur, tables):
    """Generate CREATE TABLE + constraints for the given tables."""
    out = io.StringIO()
    out.write("-- Generated by db_export.py\n")
    out.write("BEGIN;\n\n")

    # Sequences first
    cur.execute(
        """
        SELECT sequence_schema, sequence_name
          FROM information_schema.sequences
         WHERE sequence_schema IN %s
         ORDER BY sequence_schema, sequence_name
        """,
        (SCHEMAS,),
    )
    for sch, name in cur.fetchall():
        out.write(f"DROP SEQUENCE IF EXISTS {sch}.{name} CASCADE;\n")
        out.write(f"CREATE SEQUENCE {sch}.{name};\n")
    if cur.description:
        out.write("\n")

    for sch, tbl in tables:
        cur.execute(
            """
            SELECT column_name, udt_name, is_nullable, column_default,
                   character_maximum_length, numeric_precision, numeric_scale,
                   datetime_precision
              FROM information_schema.columns
             WHERE table_schema = %s AND table_name = %s
             ORDER BY ordinal_position
            """,
            (sch, tbl),
        )
        cols = cur.fetchall()
        if not cols:
            continue

        def col_ddl(row):
            name, udt, nullable, default, charlen, nprec, nscale, dtprec = row
            if udt in ("bpchar", "varchar") and charlen:
                typ = f"{udt}({charlen})"
            elif udt == "numeric" and nprec and nscale is not None:
                typ = f"numeric({nprec},{nscale})"
            elif udt in ("timestamp", "time") and dtprec:
                typ = f"{udt}({dtprec})"
            else:
                typ = udt
            parts = [f"    {name} {typ}"]
            if default is not None:
                parts.append(f"DEFAULT {default}")
            if nullable == "NO":
                parts.append("NOT NULL")
            return " ".join(parts)

        cols_ddl = ",\n".join(col_ddl(c) for c in cols)
        out.write(f"DROP TABLE IF EXISTS {sch}.{tbl} CASCADE;\n")
        out.write(f"CREATE TABLE {sch}.{tbl} (\n{cols_ddl}\n);\n")

        # Primary key
        cur.execute(
            """
            SELECT kcu.column_name
              FROM information_schema.table_constraints tc
              JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
               AND tc.table_schema = kcu.table_schema
             WHERE tc.table_schema = %s AND tc.table_name = %s
               AND tc.constraint_type = 'PRIMARY KEY'
             ORDER BY kcu.ordinal_position
            """,
            (sch, tbl),
        )
        pk = [r[0] for r in cur.fetchall()]
        if pk:
            out.write(f"ALTER TABLE {sch}.{tbl} ADD PRIMARY KEY ({', '.join(pk)});\n")

        # Unique constraints
        cur.execute(
            """
            SELECT DISTINCT tc.constraint_name, kcu.column_name
              FROM information_schema.table_constraints tc
              JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
             WHERE tc.table_schema = %s AND tc.table_name = %s
               AND tc.constraint_type = 'UNIQUE'
             ORDER BY tc.constraint_name, kcu.column_name
            """,
            (sch, tbl),
        )
        uniq = {}
        for cname, colname in cur.fetchall():
            uniq.setdefault(cname, []).append(colname)
        for cname, cols_ in uniq.items():
            out.write(
                f"ALTER TABLE {sch}.{tbl} ADD CONSTRAINT {cname} UNIQUE ({', '.join(cols_)});\n"
            )

        out.write("\n")

    # Foreign keys
    cur.execute(
        """
        SELECT con.conname, con.conrelid::regclass::text AS tbl,
               con.confrelid::regclass::text AS ref,
               a.attname AS col, af.attname AS refcol
          FROM pg_constraint con
          JOIN pg_attribute a   ON a.attrelid = con.conrelid AND a.attnum = ANY(con.conkey)
          JOIN pg_attribute af  ON af.attrelid = con.confrelid AND af.attnum = ANY(con.confkey)
         WHERE con.contype = 'f'
           AND con.conrelid::regclass::text LIKE ANY (ARRAY['public.%','storage.%'])
         ORDER BY con.conname, con.conrelid::regclass::text
        """
    )
    for cname, tbl, ref, col, refcol in cur.fetchall():
        out.write(f"ALTER TABLE {tbl} ADD CONSTRAINT {cname} FOREIGN KEY ({col}) REFERENCES {ref} ({refcol});\n")

    # Indexes
    cur.execute(
        """
        SELECT schemaname, tablename, indexname, indexdef
          FROM pg_indexes
         WHERE schemaname IN %s
         ORDER BY schemaname, tablename, indexname
        """,
        (SCHEMAS,),
    )
    for sch, tbl, iname, idef in cur.fetchall():
        if not idef.lower().startswith("create unique index") and not idef.lower().startswith("create index"):
            continue
        out.write(idef.replace('"', "") + ";\n")

    out.write("COMMIT;\n")
    return out.getvalue()


def dump_table_data(cur, sch, tbl):
    """Return gzip-compressed COPY CSV bytes of the table's rows."""
    raw_buf = io.BytesIO()
    buf = gzip.GzipFile(fileobj=raw_buf, mode="wb")
    fq = f'COPY {sql.Identifier(sch, tbl).as_string(cur)} TO STDOUT WITH (FORMAT csv, HEADER true)'
    cur.copy_expert(fq, buf)
    buf.close()
    return raw_buf.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default="backups")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    conn = connect()
    conn.autocommit = True
    cur = conn.cursor()

    info = get_server_info(cur)
    tables = list_tables(cur)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    tarball = os.path.join(args.out_dir, f"full_{stamp}.tar.gz")

    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "server_version": info.get("server_version"),
        "tables": [],
    }

    with tarfile.open(tarball, "w:gz") as tar:
        ddl = dump_ddl(cur, tables)
        def add_text(name, text):
            data = text.encode("utf-8")
            ti = tarfile.TarInfo(name)
            ti.size = len(data)
            ti.mtime = int(datetime.now().timestamp())
            tar.addfile(ti, io.BytesIO(data))

        add_text("database.sql", ddl)
        for sch, tbl in tables:
            raw = dump_table_data(cur, sch, tbl)
            manifest["tables"].append({"schema": sch, "table": tbl, "size": len(raw)})
            ti = tarfile.TarInfo(f"data/{sch}.{tbl}.csv.gz")
            ti.size = len(raw)
            ti.mtime = int(datetime.now().timestamp())
            tar.addfile(ti, io.BytesIO(raw))

        add_text("manifest.json", json.dumps(manifest, indent=2))

    cur.close()
    conn.close()
    print(f"OK: {tarball} ({len(tables)} tables, {os.path.getsize(tarball):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())